sudo: required
language:
- ruby
before_install:
- openssl aes-256-cbc -K $encrypted_d1b1c1eb7be2_key -iv $encrypted_d1b1c1eb7be2_iv
  -in read.sh.enc -out bin/read.sh -d
- gem update --system
- gem install bundler
- env
script:
- bundle install
- "./bin/read.sh.rb --test"
- chmod 755 ./bin/read.sh
- "./bin/read.sh"
